# Generated by Django 4.2.1 on 2024-06-05 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CARD', 'Card')], max_length=20, verbose_name='Payment Method')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Deposit')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Subtotal')),
                ('payment_status', models.CharField(blank=True, choices=[('BALANCE', 'Balance'), ('PAID', 'Paid'), ('CREDIT', 'Credit')], max_length=10, verbose_name='Payment Status')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Balance')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Sales Tax')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product')),
                ('vendor', models.CharField(blank=True, max_length=255, verbose_name='Vendor')),
                ('material', models.CharField(blank=True, choices=[('NATURAL QUARTZITE', 'Natural Quartzite'), ('ENGINEERED QUARTZ', 'Engineered Quartz'), ('GRANITE', 'Granite'), ('MARBLE', 'Marble'), ('DOLOMITE', 'Dolomite'), ('SOAPSTONE', 'Soapstone'), ('OTHER', 'Other')], max_length=255, verbose_name='Material')),
                ('product_is_delete', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=20, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Phone Number')),
                ('alt_phone', models.CharField(blank=True, max_length=10, verbose_name='Alt Phone Number')),
                ('company', models.CharField(blank=True, max_length=25, verbose_name='Company')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=25, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=25, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='State')),
                ('zip', models.CharField(blank=True, max_length=5, verbose_name='Zip Code')),
                ('notes', models.TextField(blank=True, verbose_name='Contact Notes')),
                ('relation', models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('DESIGNER', 'Designer'), ('CONTRACTOR', 'Contractor'), ('LEAD', 'Lead'), ('VENDOR', 'Vendor'), ('FABRICATOR', 'Fabricator'), ('OTHER', 'Other')], max_length=10, verbose_name='Relation')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='invoice.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=25, verbose_name='Product')),
                ('material', models.CharField(blank=True, choices=[('NATURAL QUARTZITE', 'Natural Quartzite'), ('ENGINEERED QUARTZ', 'Engineered Quartz'), ('GRANITE', 'Granite'), ('MARBLE', 'Marble'), ('DOLOMITE', 'Dolomite'), ('SOAPSTONE', 'Soapstone'), ('OTHER', 'Other')], max_length=25, verbose_name='Material')),
                ('vendor', models.CharField(blank=True, max_length=25, verbose_name='Vendor')),
                ('unit', models.CharField(default='ea', max_length=3, verbose_name='Unit')),
                ('qty', models.IntegerField(default=0, verbose_name='Qty')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Price')),
                ('prod_total', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Line Total')),
                ('block', models.CharField(blank=True, max_length=15, null=True, verbose_name='Block #')),
                ('length', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Length')),
                ('width', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Width')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoice.payment')),
            ],
            options={
                'verbose_name': 'Line',
                'verbose_name_plural': 'Lines',
                'unique_together': {('id', 'payment')},
            },
        ),
    ]
