# Generated by Django 4.2.1 on 2023-06-02 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_customer_address_customer_alt_phone_customer_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=255, verbose_name='Product')),
                ('unit', models.CharField(default='ea', max_length=255, verbose_name='Unit')),
                ('vendor', models.CharField(blank=True, max_length=255, verbose_name='Vendor')),
                ('product_is_delete', models.BooleanField(default=False)),
                ('material', models.CharField(blank=True, choices=[('NATURAL QUARTZITE', 'Natural Quartzite'), ('ENGINEERED QUARTZ', 'Engineered Quartz'), ('GRANITE', 'Granite'), ('MARBLE', 'Marble'), ('DOLOMITE', 'Dolomite'), ('SOAPSTONE', 'Soapstone'), ('OTHER', 'Other')], max_length=255, verbose_name='Material')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Qty')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Price')),
                ('prod_total', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Product Total')),
                ('block', models.CharField(blank=True, max_length=55, null=True, verbose_name='Block Number')),
                ('length', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Length')),
                ('width', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Width')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.product')),
            ],
        ),
    ]
