# Generated by Django 4.2.1 on 2023-06-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_product_productdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_first_name', models.CharField(blank=True, verbose_name='Contractor First Name')),
                ('contractor_last_name', models.CharField(blank=True, verbose_name='Contractor Last Name')),
                ('contractor_company', models.CharField(blank=True, max_length=55, verbose_name='Contractor Company')),
                ('contractor_phone', models.CharField(blank=True, verbose_name='Contractor Phone')),
                ('contractor_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contractor Email')),
                ('contractor_address', models.CharField(blank=True, max_length=55, verbose_name='Contractor Address')),
                ('contractor_city', models.CharField(blank=True, max_length=55, verbose_name='Contractor City')),
                ('contractor_state', models.CharField(blank=True, max_length=55, verbose_name='Contractor State')),
                ('contractor_zip', models.CharField(blank=True, max_length=9, verbose_name='Contractor Zip Code')),
                ('contractor_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='block',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Block #'),
        ),
    ]
