# Generated by Django 4.2.1 on 2023-06-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_contractor_alter_productdetail_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='contractor_address',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='contractor_city',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='contractor_state',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='contractor_zip',
        ),
        migrations.AddField(
            model_name='contractor',
            name='date_created',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
