# Generated by Django 4.2.1 on 2024-05-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_remove_contact_category_remove_invoice_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('DESIGNER', 'Designer'), ('CONTRACTOR', 'Contractor'), ('LEAD', 'Lead'), ('VENDOR', 'Vendor'), ('FABRICATOR', 'Fabricator'), ('OTHER', 'Other')], max_length=255, verbose_name='Category'),
        ),
    ]
