# Generated by Django 4.2.1 on 2024-05-23 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_productdetail_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_name',
            new_name='name',
        ),
    ]
