# Generated by Django 4.2.1 on 2024-05-23 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_alter_productdetail_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Product')),
                ('material', models.CharField(blank=True, choices=[('NATURAL QUARTZITE', 'Natural Quartzite'), ('ENGINEERED QUARTZ', 'Engineered Quartz'), ('GRANITE', 'Granite'), ('MARBLE', 'Marble'), ('DOLOMITE', 'Dolomite'), ('SOAPSTONE', 'Soapstone'), ('OTHER', 'Other')], max_length=255, verbose_name='Material')),
                ('vendor', models.CharField(blank=True, max_length=255, verbose_name='Vendor')),
                ('unit', models.CharField(default='ea', max_length=255, verbose_name='Unit')),
                ('qty', models.IntegerField(default=0, verbose_name='Qty')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Price')),
                ('prod_total', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Product Total')),
                ('block', models.CharField(blank=True, max_length=55, null=True, verbose_name='Block No.')),
                ('length', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Length')),
                ('width', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Width')),
                ('invoice', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
