# Generated by Django 4.2.1 on 2024-05-24 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_invoiceline_delete_productdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='block',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Block No'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='prod_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Line Total'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Width'),
        ),
    ]
