# Generated by Django 4.2.1 on 2024-05-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_alter_invoiceline_block_alter_invoiceline_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='category',
        ),
        migrations.AddField(
            model_name='contact',
            name='relation',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('DESIGNER', 'Designer'), ('CONTRACTOR', 'Contractor'), ('LEAD', 'Lead'), ('VENDOR', 'Vendor'), ('FABRICATOR', 'Fabricator'), ('OTHER', 'Other')], max_length=255, verbose_name='Relation'),
        ),
    ]
