# Generated by Django 4.2.1 on 2024-05-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_remove_contact_category_contact_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=25, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=25, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=25, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='relation',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('DESIGNER', 'Designer'), ('CONTRACTOR', 'Contractor'), ('LEAD', 'Lead'), ('VENDOR', 'Vendor'), ('FABRICATOR', 'Fabricator'), ('OTHER', 'Other')], max_length=10, verbose_name='Relation'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='zip',
            field=models.CharField(blank=True, max_length=5, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('BALANCE', 'Balance'), ('PAID', 'Paid'), ('CREDIT', 'Credit')], max_length=10, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CARD', 'Card')], max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='block',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Block #'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='material',
            field=models.CharField(blank=True, choices=[('NATURAL QUARTZITE', 'Natural Quartzite'), ('ENGINEERED QUARTZ', 'Engineered Quartz'), ('GRANITE', 'Granite'), ('MARBLE', 'Marble'), ('DOLOMITE', 'Dolomite'), ('SOAPSTONE', 'Soapstone'), ('OTHER', 'Other')], max_length=25, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='product',
            field=models.CharField(max_length=25, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='unit',
            field=models.CharField(default='ea', max_length=3, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='vendor',
            field=models.CharField(blank=True, max_length=25, verbose_name='Vendor'),
        ),
    ]
