# Generated by Django 4.2.1 on 2024-05-30 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_alter_contact_address_alter_contact_city_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceLine',
            new_name='Line',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
