# Generated by Django 4.2.1 on 2024-05-31 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_rename_invoiceline_line_remove_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CARD', 'Card')], max_length=20, verbose_name='Payment Method')),
                ('payment_status', models.CharField(blank=True, choices=[('BALANCE', 'Balance'), ('PAID', 'Paid'), ('CREDIT', 'Credit')], max_length=10, verbose_name='Payment Status')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Sales Tax')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Total')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Deposit')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Balance')),
                ('invoice_notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
        ),
        migrations.RemoveField(
            model_name='line',
            name='invoice',
        ),
        migrations.AddField(
            model_name='line',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.AddField(
            model_name='payment',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.contact'),
        ),
        migrations.AddField(
            model_name='line',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.payment'),
        ),
    ]
